### ISSUE TITLE
dts challeges evaluate fails

### ISSUE THREAD

**Issue by liampaull** [duckietown/challenge-aido1_LF1-template-random#2]
Here's the output:
```
Obtaining duckietown-shell from git+git://github.com/duckietown/duckietown-shell.git@v3#egg=duckietown-shell (from -r /workspace/requirements.txt (line 2))
  Cloning git://github.com/duckietown/duckietown-shell.git (to revision v3) to ./src/duckietown-shell
fatal: unable to connect to github.com:
github.com: Temporary failure in name resolution

Command "git clone -q git://github.com/duckietown/duckietown-shell.git /notebooks/src/duckietown-shell" failed with error code 128 in None
The command '/bin/sh -c pip install -r /workspace/requirements.txt' returned a non-zero code: 1
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 35, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 96, in runner_local_main_
    image = build_image(client, path, dockerfile, no_cache=no_cache, no_build=no_build)
  File "/project/src/duckietown_challenges_runner/submission_build.py", line 22, in build_image
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'build', '-t', 'myimage', '-f', './Dockerfile', '.']' returned non-zero exit status 1



dts :  message from server: Last blog post:
    :                     : 
    :                     :   Update to challenge LF, LFV evaluation code
    :                     : https://www.duckietown.org/archives/29549
ERROR:dts:Cannot get container local-evaluator: 404 Client Error: Not Found ("No such container: local-evaluator")
DEBUG:dts:monitoring graceful exit
```

**Comment by AndreaCensi** [comment]
temporary network problems
